### ISSUE TITLE
NoMethodError: undefined method `calculate_mday' for Date:Class

### ISSUE THREAD

**Issue by CloCkWeRX** [holidays/holidays#154]
holidays 3.0.0 afaik

Backtrace from newrelic:
```
NoMethodError: undefined method `calculate_mday' for Date:Class
….0/gems/holidays-3.0.0/lib/generated_definitions/au.rb:  109:in `march_pub_hol_sa'
….0/gems/holidays-3.0.0/lib/generated_definitions/au.rb:   31:in `block in holidays_by_month'
…3.0.0/lib/holidays/definition/repository/proc_cache.rb:   30:in `call'
…3.0.0/lib/holidays/definition/repository/proc_cache.rb:   30:in `lookup'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   81:in `call_proc'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   28:in `block (3 levels) in call'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   20:in `each'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   20:in `block (2 levels) in call'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   17:in `each'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   17:in `block in call'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   16:in `each'
…olidays-3.0.0/lib/holidays/use_case/context/between.rb:   16:in `call'
….bundle/ruby/2.1.0/gems/holidays-3.0.0/lib/holidays.rb:  122:in `between'
…leases/0.0.2183/app/controllers/holidays_controller.rb:    8:in `index'
```

Reproduce code
```
irb(main):003:0> Time.now
=> 2016-01-04 09:42:09 +1030
irb(main):004:0> Holidays.between(Time.now, 1.month.from_now, [:au_sa])
NoMethodError: undefined method `calculate_mday' for Date:Class
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/generated_definitions/au.rb:109:in `march_pub_hol_sa'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/generated_definitions/au.rb:31:in `block in holidays_by_month'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/definition/repository/proc_cache.rb:30:in `call'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/definition/repository/proc_cache.rb:30:in `lookup'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:81:in `call_proc'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:28:in `block (3 levels) in call'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:20:in `each'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:20:in `block (2 levels) in call'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:17:in `each'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:17:in `block in call'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:16:in `each'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays/use_case/context/between.rb:16:in `call'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/holidays-3.0.0/lib/holidays.rb:122:in `between'
	from (irb):4
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-4.1.12/lib/rails/commands/console.rb:90:in `start'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-4.1.12/lib/rails/commands/console.rb:9:in `start'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/clockwerx/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-4.1.12/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'irb(main):005:0> 
```

**Comment by CloCkWeRX** [comment]
I think it's cleaner for the definitions to invoke
```
Holidays::DateCalculatorFactory.day_of_month_calculator.call
```
even if its a lot more verbose; as it means you don't have to extend the core Date object to use the library; it becomes optional.

**Comment by ptrimble** [comment]
Gah, yeah, that's a good catch. That's a regression, I'll label it as a bug and look at your PR. Thanks for reporting!
