### ISSUE TITLE
Region for 'Jersey' / 'je' not loaded as expected

### ISSUE THREAD

**Issue by ppeble** [holidays/holidays#265]
There is a problem in some assumptions in how regions are loaded. I don't know if this is a regression or what.

Here is the command:

```ruby
irb(main):001:0> Holidays.on(Date.civil(2016, 5, 9), :je)
Holidays::UnknownRegionError: Could not load je
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/parse_options.rb:63:in `rescue in block in parse_regions!'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/parse_options.rb:55:in `block in parse_regions!'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/parse_options.rb:53:in `each'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/parse_options.rb:53:in `parse_regions!'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/parse_options.rb:20:in `call'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays/finder/context/between.rb:14:in `call'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays.rb:48:in `between'
        from /home/vagrant/dev/ppeble/holidays/lib/holidays.rb:32:in `on'
        from (irb):1
        from /home/vagrant/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

I don't see how this could EVER work without first calling some `gb*` region first. The way we load regions is heavily dependent on file names. This means that `je` has no idea that it should look in `gb.rb` to find the definitions it needs.

I don't know how to fix this yet. But I wanted to record it.

**Comment by ppeble** [comment]
As an aside, we do have an integration test to cover Jersey but...the test calls other `gb` regions first. This is why it passes. It wouldn't work otherwise.

**Comment by ppeble** [comment]
Before I forget: I think we can solve this by generating a hash of sorts into `REGIONS.rb`, that is also auto-generated. Maybe a hash that has every region as a key with its containing region(s) in it? I don't think that would be too difficult to produce and it would be quick since it would be a hash lookup.

**Comment by ppeble** [comment]
This will be addressed by the fix for https://github.com/holidays/holidays/issues/251. I'll have a PR shortly.

**Comment by ppeble** [comment]
This was addressed in https://github.com/holidays/holidays/pull/271.
